name: Full Changelog Maintenance

permissions:
  contents: write
  pull-requests: read

on:
  push:
    branches:
      - main
      - '**'        # All branches—covers all pushes
  pull_request:
    types: [opened, synchronize, closed, merged]
  merge_group:
  release:
    types: [published, edited, released]
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.2.0
        with:
          changelog_file: CHANGELOG.md     # Output file (default)
          format: markdown                 # Changelog format
          include_pr_body: true            # Include PR body in changelog
          include_labels: true             # Show labels for each PR
          fail_on_error: true              # Fail workflow on error

      - name: Diagnostics – Show Changelog Diff
        run: |
          echo "==== CHANGELOG.md DIFF ===="
          git diff CHANGELOG.md || echo "No changes detected."

      - name: Diagnostics – List Workflow Status
        run: |
          echo "Workflow completed at $(date -u)"
          git status

      - name: Commit updated CHANGELOG.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: auto-update CHANGELOG.md [skip ci]" || echo "No changes to commit"
          git push

      - name: Diagnostics – Log Success/Failure
        if: ${{ success() }}
        run: echo "Changelog CI workflow completed successfully."
      - name: Diagnostics – Log Failure
        if: ${{ failure() }}
        run: echo "Changelog CI workflow failed. Check previous step logs for details."
